name = "SMP7"
mc_version = "1.20.2"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

[variables]
PORT = "25565"
ENABLE_WHITELIST = "true"
DIFFICULTY = "hard"
SEED = "7716888065906398998"
MOTD = "                      <gradient:#c75bb4:#eac3e3><b>SMP7</b></gradient> • <white>1.20.2</white>"

[launcher]
aikars_flags = true
proxy_flags = false
nogui = true
eula_args = true

[[mods]]
type = "modrinth"
id = "audioplayer"
version = "V7VEXKMb"

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "fdestf2d"

[[mods]]
type = "modrinth"
id = "ferrite-core"
version = "unerR5MN"

[[mods]]
type = "modrinth"
id = "lithium"
version = "qdzL5Hkg"

[[mods]]
type = "modrinth"
id = "minimotd"
version = "3stGUvKr"

[[mods]]
type = "modrinth"
id = "no-chat-reports"
version = "xQyq2W5g"

[[mods]]
type = "modrinth"
id = "simple-voice-chat"
version = "bBozWUuG"

[[mods]]
type = "modrinth"
id = "lazydfu"
version = "4SHylIO9"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/afk-display?version=1.20"
filename = "afk-display.zip"
desc = "AFK Display"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/armor-statues?version=1.20"
filename = "armor-statues.zip"
desc = "Armor Statues"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/coordinates-hud?version=1.20"
filename = "coordinates-hud.zip"
desc = "Coordinates HUD"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/more-mob-heads?version=1.20"
filename = "more-mob-heads.zip"
desc = "More Mob Heads"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/multiplayer-sleep?version=1.20"
filename = "multiplayer-sleep.zip"
desc = "Multiplayer Sleep"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/nether-portal-coords?version=1.20"
filename = "nether-portal-coords.zip"
desc = "Nether Portal Coords"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/player-head-drops?version=1.20"
filename = "player-head-drops.zip"
desc = "Player Head Drops"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/silence-mobs?version=1.20"
filename = "silence-mobs.zip"
desc = "Silence Mobs"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/track-raw-statistics?version=1.20"
filename = "track-raw-statistics.zip"
desc = "Track Raw Statistics"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/track-statistics?version=1.20"
filename = "track-statistics.zip"
desc = "Track Statistics"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Terralith"
tag = "v2.4.8"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Incendium"
tag = "v5.3.3"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Nullscape"
tag = "v1.2.3"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Structory"
tag = "v1.3.3"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Structory-Towers"
tag = "v1.0.5"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Continents"
tag = "v1.1.3"
asset = "first"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns"
version = "fZUvwQng"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns-ancient-city-overhaul"
version = "uJnNm1LG"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns-pillager-outpost-rework"
version = "SoS3zxpO"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns-stronghold-rework"
version = "FvrTLmTF"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns-swamp-hut-rework"
version = "fk8rxaP1"

[[worlds.world.datapacks]]
type = "modrinth"
id = "terratonic"
version = "c3jDjKaN"

[markdown]
files = ["README.md"]
auto_update = true
