name = "SMP7"
mc_version = "1.20.4"

[jar]
type = "fabric"
loader = "0.15.7"
installer = "latest"

[variables]
PORT = "25565"
ENABLE_WHITELIST = "true"
DIFFICULTY = "hard"
SEED = "7716888065906398998"

[launcher]
aikars_flags = true
proxy_flags = false
nogui = true
eula_args = true

[[mods]]
type = "modrinth"
id = "audioplayer"
version = "fh0XFTz3"

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "htRy7kbI"

[[mods]]
type = "modrinth"
id = "ferrite-core"
version = "pguEMpy9"

[[mods]]
type = "modrinth"
id = "lazydfu"
version = "4SHylIO9"

[[mods]]
type = "modrinth"
id = "lithium"
version = "nMhjKWVE"

[[mods]]
type = "modrinth"
id = "no-chat-reports"
version = "tfv6A4l5"

[[mods]]
type = "modrinth"
id = "simple-voice-chat"
version = "aUuvK0aI"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/afk-display?version=1.20"
filename = "afk-display.zip"
desc = "AFK Display"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/armor-statues?version=1.20"
filename = "armor-statues.zip"
desc = "Armor Statues"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/coordinates-hud?version=1.20"
filename = "coordinates-hud.zip"
desc = "Coordinates HUD"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/more-mob-heads?version=1.20"
filename = "more-mob-heads.zip"
desc = "More Mob Heads"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/multiplayer-sleep?version=1.20"
filename = "multiplayer-sleep.zip"
desc = "Multiplayer Sleep"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/nether-portal-coords?version=1.20"
filename = "nether-portal-coords.zip"
desc = "Nether Portal Coords"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/player-head-drops?version=1.20"
filename = "player-head-drops.zip"
desc = "Player Head Drops"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/silence-mobs?version=1.20"
filename = "silence-mobs.zip"
desc = "Silence Mobs"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/track-raw-statistics?version=1.20"
filename = "track-raw-statistics.zip"
desc = "Track Raw Statistics"

[[worlds.world.datapacks]]
type = "url"
url = "https://vanillatweaks-api.onrender.com/datapacks/packs/track-statistics?version=1.20"
filename = "track-statistics.zip"
desc = "Track Statistics"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Terralith"
tag = "v2.4.11"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Incendium"
tag = "v5.3.4"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Nullscape"
tag = "v1.2.4"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Structory"
tag = "v1.3.4"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Structory-Towers"
tag = "v1.0.6"
asset = "first"

[[worlds.world.datapacks]]
type = "ghrel"
repo = "Stardust-Labs-MC/Continents"
tag = "v1.1.4"
asset = "first"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns"
version = "cpJzZfzm"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns-ancient-city-overhaul"
version = "klEX9Ka0"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns-pillager-outpost-rework"
version = "XrGaLF3D"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns-stronghold-rework"
version = "KDwtYgdJ"

[[worlds.world.datapacks]]
type = "modrinth"
id = "dungeons-and-taverns-swamp-hut-rework"
version = "ONK7Fotr"

[[worlds.world.datapacks]]
type = "modrinth"
id = "terratonic"
version = "ZW2e6FJs"

[markdown]
files = ["README.md"]
auto_update = true
